### ISSUE TITLE
Не работает с последней версией requests

### ISSUE THREAD

**Issue by dcroid** [viktor-gorinskiy/avito#1]
При первом и последующем запуске и смене cookies не работает с последними версиями requests.

**Comment by timikrutik** [comment]
Что делать чтобы избежать этого? Ставить старую версию?

**Comment by viktor-gorinskiy** [comment]
Если дело в версии requests, то конечно проще поставить старую версию.
Но хочу заметить, что я делал этот скрипт ради спортивного интереса. Написана соответсвующая статья на хабре.
Я никак не планирую поддерживать этот код

**Comment by timikrutik** [comment]
Прошу прощения. Не знаете ли вы, можно ли  подобным образом работать с Cian?  (Получать информацию в формате json?)

**Comment by dcroid** [comment]
@timikrutik Скорее всего можно!
